/** Shared identifiers and field-state types for academic insight packages. */
export type {
  AcademicWork,
  AcademicWorkId,
  ApprovedBriefApproval,
  Availability,
  Available,
  BriefApproval,
  ClaimId,
  ClaimAssessmentId,
  ClaimEvidenceLinkId,
  DatasetEntry,
  EvidenceCard,
  EvidenceCardId,
  EvidenceCardItem,
  EvidenceCardItemId,
  EvidenceRequirements,
  EvidenceId,
  EvidenceLevel,
  EvidenceRecord,
  EvidenceSnapshot,
  EvidenceSnapshotId,
  EvidenceSnapshotItem,
  ExecutableResearchBrief,
  ExtractionMethod,
  ExternalIdentifier,
  ExternalIdentifierDedupKey,
  ExternalIdentifierKind,
  ExternalIdentifierKindMap,
  FailureId,
  FigureLocator,
  FindingEntry,
  FindingType,
  LimitationEntry,
  LimitationType,
  MethodEntry,
  MethodRole,
  MetricDirection,
  MetricEntry,
  PageSectionLocator,
  ParagraphLocator,
  PartialDate,
  PartialDatePrecision,
  PublicationDateBasis,
  PublicationWindow,
  ProviderRecordReference,
  ProviderRecordLocator,
  PublicationStatus,
  ReportRequirements,
  ReportTargetLength,
  RequiredEvidenceLevel,
  ResearchBriefId,
  RetrievalRunId,
  SearchQueryId,
  ResearchBrief,
  ResearchQuestionEntry,
  ResearchQuestionType,
  SourceLocator,
  SourceLocatorBase,
  SourceLocatorId,
  InsufficientEvidencePolicy,
  StopConditions,
  TableLocator,
  AbstractLocator,
  WorkVersion,
  WorkVersionId,
  WorkVersionStatus,
  WorkVersionType,
} from './types.ts'

export { isAvailable } from './availability.ts'
export type {
  ClaimAssessment, ClaimAssessmentStatus, ClaimCategory, ClaimConfidence,
  ClaimEvidenceLink, ClaimEvidenceRelation, ClaimFreshnessCheck, ClaimFreshnessStatus,
  ClaimRecord, ClaimValidity,
} from './claims.ts'
export { checkClaimFreshness } from './claim-freshness.ts'
export type { ResearchStage, RetrievalRun } from './retrieval.ts'
export type { BatchResult, BatchStatus, CoverageSummary, FailureCategory, ProviderFailure } from './results.ts'
export { createBatchResult, createCoverageSummary } from './results.ts'
export { externalIdentifierDedupKey } from './external-identifiers.ts'
export {
  createAcademicWorkId,
  createClaimId,
  createClaimAssessmentId,
  createClaimEvidenceLinkId,
  createEvidenceCardId,
  createEvidenceCardItemId,
  createEvidenceId,
  createEvidenceSnapshotId,
  createFailureId,
  createResearchBriefId,
  createRetrievalRunId,
  createSearchQueryId,
  createSourceLocatorId,
  createWorkVersionId,
} from './ids.ts'
export { isExecutableResearchBrief, targetIncludedWorks } from './research-brief.ts'
export type {
  AcademicCandidateEvaluation,
  AcademicCandidateRankingResult,
  AcademicSearchQuery,
  CandidateAssessment,
  CandidateClassification,
  CandidateFulltextAvailability,
  CandidateFunnelCounts,
  CandidateHardFilterReason,
  CandidateHardFilterReasonCode,
  CandidateHardFilterResult,
  CandidatePriority,
  CandidatePriorityQueues,
  CandidatePriorityThresholds,
  CandidateRankingPolicy,
  CandidateScoreBreakdown,
  CandidateScoreValues,
  CandidateScoreWeights,
  CitationExpansionSeed,
  HybridSearchConstraints,
  HybridSearchPlan,
  HybridSearchPlanningInput,
  HybridSearchPlanningOutput,
  HybridSearchQuery,
  HybridSearchRound,
  InclusionTargets,
  QueryWorkflowPhase,
  QueryWorkflowProgressEvent,
  QuestionCoverageCounts,
  ResearchQuestionCoverage,
  ResearchQuestionCoverageResult,
  SearchQueryBase,
  SearchRoundPurpose,
  SearchStopDecision,
  SearchStopReason,
  SiteRestrictedQuery,
  WebDiscoveryQuery,
} from './query-workflow.ts'
export {
  ACADEMIC_CANDIDATE_RANKING_POLICY_V1,
  candidatePriorityForScore,
  createCandidateRankingResult,
  createCandidateScoreBreakdown,
  createInclusionTargets,
} from './query-workflow.ts'
