/** Shared identifiers and field-state types for academic insight packages. */
export type {
  AcademicWork,
  AcademicWorkId,
  ApprovedBriefApproval,
  Availability,
  Available,
  BriefApproval,
  ClaimId,
  DatasetEntry,
  EvidenceCard,
  EvidenceCardId,
  EvidenceCardItem,
  EvidenceCardItemId,
  EvidenceRequirements,
  EvidenceId,
  EvidenceLevel,
  EvidenceRecord,
  EvidenceSnapshot,
  EvidenceSnapshotId,
  EvidenceSnapshotItem,
  ExecutableResearchBrief,
  ExtractionMethod,
  ExternalIdentifier,
  ExternalIdentifierDedupKey,
  ExternalIdentifierKind,
  ExternalIdentifierKindMap,
  FailureId,
  FigureLocator,
  FindingEntry,
  FindingType,
  LimitationEntry,
  LimitationType,
  MethodEntry,
  MethodRole,
  MetricDirection,
  MetricEntry,
  PageSectionLocator,
  ParagraphLocator,
  PartialDate,
  PartialDatePrecision,
  PublicationDateBasis,
  PublicationWindow,
  ProviderRecordReference,
  ProviderRecordLocator,
  PublicationStatus,
  ReportRequirements,
  ReportTargetLength,
  RequiredEvidenceLevel,
  ResearchBriefId,
  ResearchBrief,
  ResearchQuestionEntry,
  ResearchQuestionType,
  SourceLocator,
  SourceLocatorBase,
  SourceLocatorId,
  InsufficientEvidencePolicy,
  StopConditions,
  TableLocator,
  AbstractLocator,
  WorkVersion,
  WorkVersionId,
  WorkVersionStatus,
  WorkVersionType,
} from './types.ts'

export { isAvailable } from './availability.ts'
export { externalIdentifierDedupKey } from './external-identifiers.ts'
export {
  createAcademicWorkId,
  createEvidenceCardId,
  createEvidenceCardItemId,
  createEvidenceId,
  createEvidenceSnapshotId,
  createResearchBriefId,
  createSourceLocatorId,
  createWorkVersionId,
} from './ids.ts'
export { isExecutableResearchBrief } from './research-brief.ts'
