/** Academic workflow public entry; implementations do not import this barrel. */
export { extractPaperEvidence } from './paper.ts'
export { parseEvidenceDrafts, parsePaperModelResponse } from './parse-evidence.ts'
export { createModelEvidenceGenerator } from './model.ts'
export { WorkflowLogError } from './model-errors.ts'
export type { PaperEvidenceGenerator, PaperModelResponse, PaperScopeDecision, PaperScopeRules,
  EvidenceModelSource, EvidenceModelRequest, EvidenceModelResult } from './model-types.ts'
export type { PaperEvidenceResult, PaperPause, PaperExclusion } from './types.ts'
export { runResearchDraft } from './pipeline.ts'
export { runModelResearchDraft } from './model-pipeline.ts'
export { runAcademicResearchDraft } from './entry.ts'
export { selectResearchPapers } from './selection.ts'
export type { PaperCandidateResolver } from './selection.ts'
export type { AcademicResearchDraftRequest, AcademicResearchDraftResult } from './entry.ts'
export type { DraftPipelineAdapters, DraftPipelineInput, DraftPipelineResult, SelectedPaper, PaperProcessingFailure } from './pipeline-types.ts'
