/** Standalone HTML report artifact; no live Web plugin, backend, or model requests. */
import type { ResearchReport } from '@deepseek-ai/dsh-academic-report'
import { labels } from './locales.ts'

function escapeHtml(value: string): string {
  return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;')
}

/**
 * Render a self-contained, searchable report with a Markdown download button.
 * @param report Evaluated report generated by academic-report.
 * @param language Viewer chrome language; research content remains verbatim.
 * @returns HTML with escaped content and no external assets or network calls.
 */
export function renderResearchPage(report: ResearchReport, language: keyof typeof labels): string {
  const t = labels[language]
  const claims = report.claims.map((claim, index) => `<article class="searchable" id="claim-${index}">
    <h3>${index + 1}. ${escapeHtml(claim.category)}</h3><p class="claim-text">${escapeHtml(claim.text)}</p>
    <p>${escapeHtml(claim.scope)}</p><small>${t.confidence}: ${escapeHtml(claim.confidence)}</small>
    <p>${escapeHtml(claim.confidenceReasons.join(' · '))}</p>
    <div>${claim.evidenceSnapshot.evidenceItems.map(item => `<a class="chip" href="#evidence-${escapeHtml(item.evidenceId)}">${escapeHtml(item.evidenceId)}</a>`).join(' ')}</div></article>`).join('')
  const evidence = report.evidence.map(record => `<details class="searchable" id="evidence-${escapeHtml(record.evidenceId)}">
    <summary>${escapeHtml(record.evidenceId)} · ${escapeHtml(record.level)}</summary>
    <p>${t.version}: ${escapeHtml(record.workVersionId)}</p><p>${t.source}: ${escapeHtml(record.sourceUrl)}</p>
    <blockquote>${escapeHtml(record.verbatimExcerpt.status === 'available' ? record.verbatimExcerpt.value : t.excerpt)}</blockquote>
    <p>${escapeHtml(record.qualityNotes.join(' · '))}</p></details>`).join('')
  const data = JSON.stringify({ markdown: report.markdown }).replaceAll('<', '\\u003c')
  return `<!doctype html><html lang="${language}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>${escapeHtml(report.title)}</title><style>
    :root{color-scheme:light dark}*{box-sizing:border-box}body{margin:0;background:Canvas;color:CanvasText;font:16px/1.65 system-ui,sans-serif}
    header,main{max-width:1120px;margin:auto;padding:28px}header{border-bottom:1px solid GrayText}h1{font-size:clamp(26px,4vw,42px);line-height:1.2}
    nav{display:flex;gap:18px;flex-wrap:wrap;margin:20px 0}a{color:LinkText}button,input{font:inherit;padding:10px 15px;border-radius:8px;border:1px solid GrayText}
    button{cursor:pointer}input{width:min(100%,520px)}.status,.chip{display:inline-block;padding:3px 10px;border:1px solid GrayText;border-radius:8px;margin:4px 6px 4px 0}
    section{margin:30px 0}article,details{padding:20px;border:1px solid GrayText;border-radius:12px;margin:15px 0;overflow-wrap:anywhere}
    h2{font-size:24px}h3{margin-top:0}.claim-text{white-space:pre-line}blockquote{margin:15px 0;padding-left:16px;border-left:3px solid GrayText}
    summary{cursor:pointer}small{font-size:14px}pre{white-space:pre-wrap;overflow-wrap:anywhere}.toolbar{display:flex;gap:12px;flex-wrap:wrap}
    [hidden]{display:none!important}@media(max-width:600px){header,main{padding:18px}article,details{padding:14px}}
    </style></head><body><header><small>${t.title} / ${report.mode === 'draft' ? t.draft : t.final}</small>
    <h1>${escapeHtml(report.title)}</h1>${report.synthetic ? `<p>${t.synthetic}</p>` : ''}
    <span class="status">${t[report.evaluation.status]}</span><nav aria-label="${t.navigation}"><a href="#claims">${t.claims}</a><a href="#evidence">${t.evidence}</a><a href="#quality">${t.limits}</a></nav>
    <div class="toolbar"><input id="search" type="search" aria-label="${t.search}" placeholder="${t.search}"><button id="download">${t.download}</button></div></header>
    <main><section id="claims"><h2>${t.claims}</h2>${claims || `<p>${t.none}</p>`}</section>
    <section id="evidence"><h2>${t.evidence}</h2>${evidence}</section>
    <section id="quality"><h2>${t.limits}</h2><ul>${report.limitations.map(text => `<li>${escapeHtml(text)}</li>`).join('')}</ul>
    ${report.evaluation.assessments.map(item => `<p>${escapeHtml(item.status)}: ${escapeHtml(item.reason)}</p>`).join('')}</section>
    <details><summary>${t.markdown}</summary><pre>${escapeHtml(report.markdown)}</pre></details></main>
    <script id="report-data" type="application/json">${data}</script><script>
    const report = JSON.parse(document.getElementById('report-data').textContent);
    document.getElementById('search').addEventListener('input', event => {
      const query = event.target.value.toLocaleLowerCase();
      document.querySelectorAll('.searchable').forEach(item => { item.hidden = !item.textContent.toLocaleLowerCase().includes(query); });
    });
    document.querySelectorAll('a[href^="#evidence-"]').forEach(link => link.addEventListener('click', () => {
      const target = document.getElementById(link.getAttribute('href').slice(1));
      if (target) { target.hidden = false; target.open = true; }
    }));
    document.getElementById('download').addEventListener('click', () => {
      const url = URL.createObjectURL(new Blob([report.markdown], {type:'text/markdown;charset=utf-8'}));
      const link = document.createElement('a');link.href = url;link.download = 'academic-report.md';
      document.body.appendChild(link);link.click();link.remove();setTimeout(() => URL.revokeObjectURL(url), 1000);
    });</script></body></html>`
}
